language: c++
script:
  - qmake $QMAKE_ARGS; make

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
      before_install:
        - brew update
      install:
        - brew install qt5; brew link --force qt5
    - os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -y qt5-default qt5-qmake qtbase5-dev-tools qtmultimedia5-dev zlib1g-dev
    - os: linux
      sudo: required
      dist: trusty
      before_install:
        - sudo dpkg --add-architecture i386
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -y qtchooser qtbase5-dev:i386 qtmultimedia5-dev:i386 qt5-qmake:i386 qtbase5-dev-tools:i386
        - sudo apt-get install -y g++-multilib zlib1g-dev:i386
      env:
        - QMAKE_ARGS="-qt=qt5-i386-linux-gnu -spec linux-g++-32 INCLUDEPATH+=/usr/include/x86_64-linux-gnu/c++/4.8/32/"
