version: 0.0.5#{build}
image: Visual Studio 2015
init:
- cmd: >-
    SET PATH=%PATH%;C:\Qt\5.6\msvc2015\bin;"C:\Program Files (x86)\Inno Setup 5"

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"
install:
- ps: >-
    $opensslVersion = "1.0.2j"

    choco install innosetup

    [Environment]::CurrentDirectory = $PWD

    $opensslName = "openssl-$opensslVersion-vs2015"

    $opensslDownloadUrl = "http://www.npcglib.org/~stathis/downloads/$opensslName.7z"

    $wc = New-Object net.webclient

    $wc.Downloadfile($opensslDownloadUrl, "$opensslName.7z")

    7z x "$opensslName.7z"

    Rename-Item "$opensslName" openssl
build_script:
- cmd: >-
    qmake OpenRCT2Launcher.pro

    nmake

    mkdir build-Windows

    copy release\OpenRCT2.exe build-Windows\OpenRCT2.exe

    windeployqt build-Windows\OpenRCT2.exe

    copy openssl\bin\libeay32MD.dll build-Windows\libeay32.dll

    copy openssl\bin\ssleay32MD.dll build-Windows\ssleay32.dll

    pushd build-Windows & 7z a -tzip ..\OpenRCT2Launcher-win.zip * & popd

    iscc installer.iss
artifacts:
- path: OpenRCT2Launcher-win.zip
  name: zip-archive
- path: OpenRCT2Launcher-win.exe
  name: exe-installer
deploy:
- provider: GitHub
  auth_token:
    secure: U+ZR9yj0ExiwkxNQ5o/zhtschZ/kktjWmTMilMfbHCcD0dlyBYDVUCjQWbQ8jiA7
  artifact: zip-archive, exe-installer
  on:
    appveyor_repo_tag: true