version: 0.0.5#{build}
image: Visual Studio 2015
environment:
  matrix:
  - VC_ARCH: x86
    QT_PATH: C:\Qt\5.7\msvc2015
    SSL_BUILD: jjlsys3xhwn410sw
    INNO_ARGS: 
  - VC_ARCH: amd64
    QT_PATH: C:\Qt\5.7\msvc2015_64
    SSL_BUILD: r2cuqxx95y9bcrwk
    INNO_ARGS: /DBUILD64
install:
- ps: >-
    choco install innosetup

    [Environment]::CurrentDirectory = $PWD

    $opensslDownloadUrl = "https://ci.appveyor.com/api/buildjobs/$Env:SSL_BUILD/artifacts/OpenSSL-DLLs.zip"

    $wc = New-Object net.webclient

    $wc.Downloadfile($opensslDownloadUrl, "OpenSSL-DLLs.zip")

    7z e "OpenSSL-DLLs.zip"
build_script:
- cmd: >-
    SET PATH=%PATH%;%QT_PATH%\bin;"C:\Program Files (x86)\Inno Setup 5"

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %VC_ARCH%

    qmake OpenRCT2Launcher.pro

    nmake

    mkdir build-Windows

    copy release\OpenRCT2.exe build-Windows\OpenRCT2.exe

    windeployqt build-Windows\OpenRCT2.exe

    copy libeay32.dll build-Windows\

    copy ssleay32.dll build-Windows\

    pushd build-Windows & 7z a -tzip ..\OpenRCT2Launcher-win.zip * & popd

    iscc %INNO_ARGS% installer.iss
artifacts:
- path: OpenRCT2Launcher-win.zip
  name: zip-archive
- path: OpenRCT2Launcher-win.exe
  name: exe-installer
deploy:
- provider: GitHub
  auth_token:
    secure: U+ZR9yj0ExiwkxNQ5o/zhtschZ/kktjWmTMilMfbHCcD0dlyBYDVUCjQWbQ8jiA7
  artifact: zip-archive, exe-installer
  on:
    appveyor_repo_tag: true