version: 0.0.4#{build}
os: Visual Studio 2013
install:
- cmd: >-
    SET PATH=%PATH%;C:\Qt\5.5\msvc2013\bin

    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd.bat"
build_script:
- cmd: >-
    qmake

    nmake